### ISSUE TITLE
fish shell contributors discussion

### ISSUE THREAD

**Issue by ridiculousfish** [ilyash/ngs#10]
The author of this repo has reached out to fish shell contributors. This issue is a place to collect their feedback. (It's not really an issue per se, but I'm not sure if there's any better way to have a discussion.)

**Comment by ridiculousfish** [comment]
My reading of the main vision of this project is to have a shell with a strong programming component specialized for "cloud" tasks, especially remote server management. Having a focused vision is great, and I agree this is an underserved niche.

My biggest concern about this is its enormous scope. You have a lot of great ideas, and you're trying to put them all in at once! Consider how you will break it down. What will the 1.0 release look like? Which of your features are targeted for that release, and which for a later one?

You have three distinct projects here: an ambitious programming language, a very ambitious interactive shell, and a web-based terminal. Trying to do all three at once is going to be overwhelming. Consider aiming for just one of those, all the way through a 1.0 release.

The list of interactive features is also ambitious, especially the decision to have distinct web and terminal UIs. I would suggest focusing on one (web or terminal) all the way through any 1.0 release. If you choose terminal, expect to bump up against its limitations often.

I also would suggest listing some *non-goals*: ways that you achieve simplification, things you deliberately are choosing to not support to make this project feasible.

**Comment by faho** [comment]
I agree with everything fish has said, but I also have something of my own to add:

I don't quite understand how interoperating with current tools is going to work - that's presumably a goal of this?

For instance:

>Not to block, allow typing next commands even if previous command(s) still run(s).

How should this work if a command expects keyboard input? In your own UI (i.e. not hosted in a terminal) you can basically do window management (e.g. allow clicking inside emacs' "window" and then redirect input to it until the user clicks back to the commandline), but inside a terminal that won't (IIUC) work.

Similarly:

>Most of the data dealt with is tables. List of files, list of instances in a cloud, list of load balancers. Amazing that none of current shell tools (I heard of) don't treat the data as such.

This is a _really_ hard problem. It means you need to either expect tools to be written for you or you need to write a "transformation script". Also, powershell is an obvious example of prior art here.

Additionally, if you want to attract more contributors and testers and users in general, you'll probably want to add more example to the documentation. How would I use this to e.g. perform an operation on a specific set of files (i.e. something you'd use globs or `find` for).

**Comment by ilyash** [comment]
Thanks guys!

**Vision, scope and milestones**.

I will be organizing my thoughts and documentation regarding this issue. Currently [the todo file](https://github.com/ilyash/ngs/blob/master/c/todo.txt) only lists two major phases: programming and CLI. I guess I'll be splitting the phases into more specific milestones. The Web console is currently postponed and the plan is to make the terminal work much like the web demo.

The biggest part of the programming language is already implemented so the nearest milestone should probably be called, "programmin" while one of the next milestones would be "cloud programming" (not sure about the title, sounds too bombastic).

Actually I'm not thinking about the programming language as "ambitious". The only special part is convenient remote execution. The rest is just a mix of bash and other languages, focused on the domain-sepcific tasks with very few important unique features (yet?).

**Non goals**

Type system should not reach the comlexity of Scala's type system. While describing function parameters, it might be convenient to express that you are expecting an array of certain type or a hash with keys and values of certain type (not implemented yet, can be done with `guard`). That's border-line. Anything more complex than types of elements in arrays and hashes is not worth it.

Can't think of anything else now.

**Terminal and programs input**

I'd like the terminal to function very much like the web demo. The shell will be managing areas of the screen and let you switch and direct input to a specific program. There should probably a list of applications that should run "full-screen" - editors and such. This needs POC. Note that besides such "full-screen" programs, very little number of other programs are interactive so investing much time in perfect solution here is not a priority.

**Tabular data**

I'm dreaming of interoperability here. Yes, existing tools should either be adapted or wrapped with a "transformation script".

NGS scripts would use output library which will behave differently for "regular" terminal output and when inside the shell, providing either textual and structured data output. If I did it right, the [`Table`](https://github.com/ilyash/ngs/blob/master/c/autoload/Table.ngs) is the beginning of such output library. (Currently `Table` only handles output to a TTY, todo: output as "conventional" JSON and output as tabular data JSON or otherwise serialized for NGS). Similar libraries could be provided for bash and other languages I guess.

A wrapper script example is then [ec2din.ngs](https://github.com/ilyash/ngs/blob/master/c/demo/ec2din.ngs).

Many tabular data is returned from scripts as a JSON with array of records. NGS could detect this. Providing one-time interactive configurator that saves which columns to display and in which order should be a good solution for some of such outputs.

I was not and still not sure what's going in PowerShell. It looks like they can pass arrays of records and the only tool that deals with this as a table is `Format-Table`. My vision is to be able to manipulate tabular data with awk-like programming and display it for interactive work (think navigating to instance_id in instances list and pressing Enter would bring a menu: Start/Stop/Terminate/Launch more like this/...). I'm not seeing this in PowerShell (from the quick search I did now).

**Comment by faho** [comment]
>Type system should not reach the comlexity of Scala's type system. While describing function parameters, it might be convenient to express that you are expecting an array of certain type or a hash with keys and values of certain type (not implemented yet, can be done with guard).

And again: How do you envision your type system working with external commands? Because those expect everything like bash hands it to them - as a string. Do you expect having to write wrapper scripts for this, too? 

>I was not and still not sure what's going in PowerShell. It looks like they can pass arrays of records and the only tool that deals with this as a table is Format-Table.

From https://msdn.microsoft.com/powershell/scripting/getting-started/cookbooks/using-format-commands-to-change-output-view:

```powershell
PS> Get-Process -Name powershell | Format-List -Property ProcessName,FileVersion
,StartTime,Id

ProcessName : powershell
FileVersion : 1.0.9567.1
StartTime   : 2006-05-24 13:42:00
Id          : 2760

ProcessName : powershell
FileVersion : 1.0.9567.1
StartTime   : 2006-05-24 13:54:28
Id          : 3448
```

That's basically what you want, no?

**Comment by ilyash** [comment]
The type system is mostly used in methods definitions for multi-dispatch. Your question is regarding how I understand what's the semantics of output of other scripts I guess. Wrapper scripts or more probable hook functions in NGS.

I see now that PowerShell does something very close to what I'm talking about: not `awk ... { print $7}` but `Get-Process | Where-Object {$_.handles -gt 200}` ( https://technet.microsoft.com/en-us/library/ee177028.aspx )

**Comment by ilyash** [comment]
Thanks guys! I'll continue working on the roadmap. Closing this issue. Feel free to re-open if you have more feedback.
