### ISSUE TITLE
Consider making Python the programming language of NGS 

### ISSUE THREAD

**Issue by Wingie** [ilyash/ngs#12]
I've been looking over the project and find it has tremendous potential. I agree with your premise that there is much scope for improvement over current shells like zsh, fishshell etc.

However, it seems to me that there would be a significant gain in adopting an already existing language such as python as the 'programming language' of the shell.
https://docs.python.org/2/extending/embedding.html

I think there would be both advantages and disadvantages to such an approach and i'll just try and list them out here.

Advantages

1. DRY compliant as we can fully leverage the features of python inside the shell instead of reinventing a programming language from scratch.
2. Low barrier of entry for new developers as it is not required to learn the syntax of another programming language at the bash level. - this would theoretically lead to higher adoptions.
3. Python already has very good shell functionality (see ipython) 
4. Possible extensible plugin architecture for people to extend functionality of the shell via python snippets hence allowing for customizability. 

Disadvantages

1. Syntax and Architecture would be more complicated
2. Not as 'cool' as designing a full featured programming language from scratch
3. Combining python syntax as well as execution results, I/O etc. might be complicated to handle.
4. Is a massive change in direction for NGS.

Example Usage Scenarios

1. file manipulation
```
# store directory listing in a variable

> ls = files_list      

# loop through every image file
# make a directory by converting '_' into multilevel folder structure
# move the file into that created folder and rename it 

> for file in files_list.filter(extension='jpg'):
    dir_name = '/'.join(file.split('_'))
    mkdir -p dir_name
    mv file dir_name/file.split('_')[-1]
```

2. log folder maintenance

```
> ls = files_list 
> date=datetime.strftime('%d-%m-%y')
> tar -xvzf files_list.filter(extension='log') > logs_{date}.tar.gz
> s3cmd put logs_{date}.tar.gz --bucket='backup'
> rm files_list logs_{date}.tar.gz
```

**Comment by ilyash** [comment]
I have considered basing my project on an existing language when I started. It is not good enough. I don't see any way to adapt any existing language in a way that would lead to optimal domain specific language.

Also, there is a Python based shell project already: [Xonsh](http://xon.sh/)

> Low barrier of entry

It will be higher with NGS. I'm trying to balance this with making the language feel and function close to other existing languages where possible.

> Python already has very good shell functionality

Not anywhere near what I'm planning, so it's a relatively small advantage.

> Possible extensible plugin architecture

Will be in place. Note that the NGS shell will be in the NGS language. Using NGS language will be better for extending (than say Python) as NGS was planned to be easily extendable: each function call is a potential extension point.

> Not as 'cool' 

NGS language is for functionality and best fit for system tasks, not because it's cool

> Is a massive change in direction for NGS.

Not a problem if I'm convinced in better results. Right now I think the only viable option is ground-up language for system tasks.

In addition, specifically Python is a bit problematic as a shell language because system guys and girls like one-liners.

Let's call your suggested language NGS2 for the sake of this discussion.
If you have spare time, you are welcome to write a small part of such extensions to the Python language to create minimal version of NGS2. Then try to re-implement some scripts from the c/demo folder in NGS2 to compare and see how it feels like. Or try writing the demo scripts in Xonsh and see how it compares. My estimation is that the NGS version would feel better. Estimations are cool but if we had something to compare to - it would be much better :)

**Comment by ilyash** [comment]
I'd really like to see some scripts to compare. Feel free to re-open if you have any new thoughts.
